export const GET_PRODUCTS_SINGLEPAGE_REQUEST = "GET_PRODUCTS_SINGLEPAGE_REQUEST";
export const GET_PRODUCTS_SINGLEPAGE_SUCCESS = "GET_PRODUCTS_SINGLEPAGE_SUCCESS";
export const GET_PRODUCTS_SINGLEPAGE_ERROR = "GET_PRODUCTS_SINGLEPAGE_ERROR";