
//CART
export const ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE="ADD_TO_CART_FAILURE";

export const DELETE_ITEM_REQUEST="DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS="DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE="DELETE_ITEM_FAILURE";

export const QUANTITY_UPDATE_REQUEST="QUANTITY_UPDATE_REQUEST";
export const QUANTITY_UPDATE_SUCCESS="QUANTITY_UPDATE_SUCCESS";
export const QUANTITY_UPDATE_FAILURE="QUANTITY_UPDATE_FAILURE";

export const GET_CART_ITEM_REQUEST="GET_CART_ITEM_REQUEST";
export const GET_CART_ITEM_SUCCESS="GET_CART_ITEM_SUCCESS";
export const GET_CART_ITEM_FAILURE="GET_CART_ITEM_FAILURE";